-- ════════════════════════════════════════════════
-- BlancoGestión — Tabla: ventas
-- Ejecutar en Supabase > SQL Editor
-- ════════════════════════════════════════════════

create table public.ventas (
  id              bigint generated by default as identity not null,
  created_at      timestamp with time zone not null default now(),
  producto_id     bigint references public.productos(id) on delete set null,
  cantidad        integer not null default 1,
  precio_unitario numeric null,
  total           numeric null,
  estado          text not null default 'completed',  -- 'completed' | 'pending'
  detalle         text null,
  constraint ventas_pkey primary key (id)
) tablespace pg_default;

-- Índices para filtrar rápido
create index ventas_created_at_idx  on public.ventas (created_at desc);
create index ventas_producto_id_idx on public.ventas (producto_id);
create index ventas_estado_idx      on public.ventas (estado);

-- RLS: permitir al rol anon leer e insertar (ajustá según tu auth)
alter table public.ventas enable row level security;

create policy "Allow anon read"   on public.ventas for select using (true);
create policy "Allow anon insert" on public.ventas for insert with check (true);
create policy "Allow anon update" on public.ventas for update using (true);
